services:
  - type: web
    name: estudios-epidemiologicos
    env: static
    staticPublishPath: .
    buildCommand: echo "No build needed"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
